# .github/workflows/cicd-security-analysis.yaml

default_options: "--persona=pedantic"

repositories:
  - name: fluttercandies/flutter_tilt
    enabled: true
    options: ""
    assignees: [AmosHuKe]
